name: Update README with Dev.to Posts
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: '4'
          feed_list: 'https://dev.to/feed/tarzanlevrai'
          commit_message: 'Update README with latest Dev.to posts'
